package com.bookstore.model;

// Import necessary JPA and validation annotations
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a Book entity in the database.
 */
@Entity  // Marks this class as a JPA entity (table in the database)
@Getter  // Lombok annotation to generate getter methods automatically
@Setter  // Lombok annotation to generate setter methods automatically
@NoArgsConstructor  // Lombok annotation to generate a no-args constructor
public class Book {

    /**
     * Primary key for the Book entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the book.
     * - Cannot be blank (validated using @NotBlank).
     * - Cannot be null (enforced by @Column(nullable = false)).
     * - Maximum length: 100 characters.
     */
    @NotBlank(message = "Title cannot be blank")
    @Column(nullable = false, length = 100)
    private String title;

    /**
     * The author of the book.
     * - Cannot be blank (validated using @NotBlank).
     * - Cannot be null (enforced by @Column(nullable = false)).
     * - Maximum length: 50 characters.
     */
    @NotBlank(message = "Author cannot be blank")
    @Column(nullable = false, length = 50)
    private String author;

    /**
     * The unique ISBN (International Standard Book Number) of the book.
     * - Must be unique (enforced by @Column(unique = true)).
     * - Cannot be null (enforced by @Column(nullable = false)).
     * - Maximum length: 13 characters.
     */
    @Column(unique = true, nullable = false, length = 13)
    private String isbn;

    /**
     * Constructor to create a Book with title, author, and ISBN.
     * 
     * @param title  The title of the book.
     * @param author The author of the book.
     * @param isbn   The ISBN of the book.
     */
    public Book(String title, String author, String isbn) {
        this.title = title;
        this.author = author;
        this.isbn = isbn;
    }
}
